### ISSUE TITLE
Missing Dockerfile + fix

### ISSUE THREAD

**Issue by marcvanraalte** [alliander-opensource/openstf-reference#13]
Attached in the zip file, I propose a fix in the .yml file and the missing Dockerfile to build the influx-configurator image and to deploy it.
Kind regards,
Marc 
[Dockerfile-docker-compose.zip](https://github.com/OpenSTEF/openstef-reference/files/8371206/Dockerfile-docker-compose.zip)

**Comment by sylvlecl** [comment]
Hi all,

Isn't the right fix to remove the "build" section from the docker-compose file ?
(Possibly moving the shm_size instructions at the service level, instead of build)

`docker-compose up` worked fine for me after removing that part.
Best regards,
Sylvain

**Comment by FrankKr** [comment]
fixed by Sander3003
